#!/usr/bin/env bash
# --------------------------------------------------------------------------------------------------
# Licensing
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Description
#   Auto-completion script for the colorex command.
# --------------------------------------------------------------------------------------------------

_colorex()
{
  cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $( compgen -W "--version -h --help -b --blue= -r RED --red= -g --green= -y --yellow= -m --magenta= -c --cyan= -B --bblue= -R --bred= -G --bgreen= -Y --byellow= -M --bmagenta= -C --bcyan= -K --blink= -D --bold= -N --bisounours" -- $cur ) )
}

complete -o nospace -F _colorex colorex
