.TH COLOREX 1 "May 23, 2010"


.SH NAME
colorex \- Colorize commands output using patterns.


.SH SYNOPSIS
.B colorex
[options...] -- command [args...]

some-command |
.B colorex
[options...]


.SH DESCRIPTION
Display commands output colored matching words or regular expressions. If you don't specify a command, STDIN is used.


.SH OPTIONS
These programs follow the usual GNU command line syntax, with long options starting with two dashes (`-'). A summary of
options is included below.

.PP
.B
Common options

.TP
.B
    \-v, \-\-version
    show program's version number and exit

.TP
.B
    \-h, \-\-help
    show this help message and exit

.TP
.B
    \-v, \-\-verbose
    Turn on verbose mode. This option can be called several times to increase the verbosity level.

.TP
.B
    \-f CONFIG, \-\-config CONFIG
    Load a config file defining patterns. Go to /usr/share/colorex/configs for examples. The option can be called
    several times.

.TP
.B
    \-\-disable\-stderr\-filtering
    Disable STDERR filtering, which can have unexpected effects on commands directly using tty (such as top).

.PP
.B
Foreground color
\- Use these options to associate patterns to text foreground colors.

.TP
.B
    \-r RED, \-\-red RED
    display RED pattern in red

.TP
.B
    \-g GREEN, \-\-green GREEN
    display GREEN pattern in green

.TP
.B
    \-y YELLOW, \-\-yellow YELLOW
    display YELLOW pattern in yellow

.TP
.B
    \-b BLUE, \-\-blue BLUE
    display BLUE pattern in blue

.TP
.B
    \-m MAGENTA, \-\-magenta MAGENTA
    display MAGENTA pattern in magenta

.TP
.B
    \-c CYAN, \-\-cyan CYAN
    display CYAN pattern in cyan

.TP
.B
    \-\-start\-red START_RED
    toggle foreground color to red at START_RED pattern

.TP
.B
    \-\-start\-green START_GREEN
    toggle foreground color to green at START_GREEN pattern

.TP
.B
    \-\-start\-yellow START_YELLOW
    toggle foreground color to yellow at START_YELLOW pattern

.TP
.B
    \-\-start\-blue START_BLUE
    toggle foreground color to blue at START_BLUE pattern

.TP
.B
    \-\-start\-magenta START_MAGENTA
    toggle foreground color to magenta at START_MAGENTA pattern

.TP
.B
    \-\-start\-cyan START_CYAN
    toggle foreground color to cyan at START_CYAN pattern

.TP
.B
    \-\-reset\-color RESET_COLOR
    reset foreground color at RESET_COLOR pattern

.PP
.B
Background color
\- Use these options to associate patterns to text background colors.

.TP
.B
    \-R BRED, \-\-bred BRED
    display BRED pattern in red background

.TP
.B
    \-G BGREEN, \-\-bgreen BGREEN
    display BGREEN pattern in green background

.TP
.B
    \-Y BYELLOW, \-\-byellow BYELLOW
    display BYELLOW pattern in yellow background

.TP
.B
    \-B BBLUE, \-\-bblue BBLUE
    display BBLUE pattern in blue background

.TP
.B
    \-M BMAGENTA, \-\-bmagenta BMAGENTA
    display BMAGENTA pattern in magenta background

.TP
.B
    \-C BCYAN, \-\-bcyan BCYAN
    display BCYAN pattern in cyan background

.TP
.B
    \-\-start\-bred START_BRED
    toggle background color to red at START_BRED pattern

.TP
.B
    \-\-start\-bgreen START_BGREEN
    toggle background color to green at START_BGREEN pattern

.TP
.B
    \-\-start\-byellow START_BYELLOW
    toggle background color to yellow at START_BYELLOW pattern

.TP
.B
    \-\-start\-bblue START_BBLUE
    toggle background color to blue at START_BBLUE pattern

.TP
.B
    \-\-start\-bmagenta START_BMAGENTA
    toggle background color to magenta at START_BMAGENTA pattern

.TP
.B
    \-\-start\-bcyan START_BCYAN
    toggle background color to cyan at START_BCYAN pattern

.TP
.B
    \-\-reset\-bcolor RESET_BCOLOR
    reset background color at RESET_BCOLOR pattern

.PP
.B
Text intensity
\- Use these options to associate patterns to text emphasis.

.TP
.B
    \-\-bold BOLD
    display BOLD pattern in bold

.TP
.B
    \-\-faint FAINT
    display FAINT pattern with decreased intensity

.TP
.B
    \-\-start\-bold START_BOLD
    toggle bold on at START_BOLD pattern

.TP
.B
    \-\-start\-faint START_FAINT
    toggle faint on at START_FAINT pattern

.TP
.B
    \-\-reset\-intensity RESET_INTENSITY
    reset text intensity at RESET_INTENSITY pattern

.PP
.B
Other formattings
\- Use these options to associate patterns to text formattings. Some of the filters may not work on all terminals.

.TP
.B
    \-\-italic ITALIC
    display ITALIC pattern in italic

.TP
.B
    \-\-underline UNDERLINE
    display UNDERLINE pattern underlined

.TP
.B
    \-\-underline\-double UNDERLINE_DOUBLE
    display UNDERLINE_DOUBLE pattern double underlined

.TP
.B
    \-\-blink BLINK
    display BLINK pattern blinking

.TP
.B
    \-\-blink-rapid BLINK_RAPID
    display BLINK pattern blinking

.TP
.B
    \-\-negative NEGATIVE
    display NEGATIVE pattern swapping foreground and background

.TP
.B
    \-\-hide HIDE
    hide HIDE pattern


.SH EXAMPLES

.TP
Colorize the 'diff' command output using the provided config:
colorex diff file1 file2

.TP
Colorize the 'ping' command output using the provided config:
colorex ping www.google.com

.TP
Ping Google with IP addresses colorized in red:
colorex \-\-red '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' \-\- ping www.google.com

.TP
Pipe content to colorex instead of providing a command:
tail -f my-file.log | colorex \-\-config my-config

.PP
If the target command attributes are ambiguous with colorex ones, make sure to separate them with '\-\-' as the examples
show.

.SH CONFIGS
.TP
The \-f or \-\-config option allows to load patterns defined in a configuration file, for example:
colorex \-\-config MY_CONFIG
.PP
colorex will look for the config at the following places, in the following order:
  * MY_CONFIG
  * MY_CONFIG.cfg
  * ~/.colorex/MY_CONFIG
  * ~/.colorex/MY_CONFIG.cfg
  * /usr/share/colorex/configs/MY_CONFIG
  * /usr/share/colorex/configs/MY_CONFIG.cfg

colorex comes bundled with several configs, for example for the ping, top and diff commands, for Tomcat/JBoss logs, etc.
These configs are located at /usr/share/colorex/configs and can serve as examples. You can override the default configs
with your own ones by placing them in ~/.colorex.


.SH BUGS
Please report bugs to http://bugs.launchpad.net/colorex.


.SH AUTHOR
.PP
This manual page was written by Julien Nicoulaud <julien.nicoulaud@gmail.com>,
for the colorex project (http://launchpad.net/colorex), and may be used
by others.
